### ISSUE TITLE
to be github action

### ISSUE THREAD

**Issue by YMC-GitHub** [YMC-GitHub/ymc-github#2]
## desc

to be a github action in the reppo

## content

use github workflow as below:
```yaml
- uses: ymc-github/ymc-github@main
   with: 
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.ref }}
```
